# Ball settings
INITIAL_BALL_SPEED_Y =1
BALL_SPEED_INCREASE_AMOUNT = .5
BALL_SPEED_INCREASE_INTERVAL = 5

# Ball spawning settings
BALL_SPAWN_INTERVAL = 0.6 

# Timer settings
GAME_DURATION = 30  
PREPARATION_TIME = 2
